--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,4 +30,4 @@
         run: cargo build --verbose
 
       - name: Test
-        run: cargo test --workspace --verbose
+        run: cargo test --workspace --verbose